import { assert, digest, newId, sealPlain } from './core.mjs';
import { assertIndependentVerifier } from './authority.mjs';
function defaultIdentity(a){return {provider:a.provider??null,model:a.model??null,identityDigest:digest({id:a.id,provider:a.provider??null,model:a.model??null,command:a.command??null,args:a.args??[]},'agent_identity')};}
export async function runArmadaTournament({mission,lane,agents,executor,verifier,trials,baseSha=null,resolveAgentIdentity=null}){
  assert(typeof executor==='function','executor adapter required');assert(typeof verifier==='function','independent verifier adapter required');assert(Array.isArray(agents)&&agents.length>=2,'at least two agents required for an Armada tournament');assert(Array.isArray(trials)&&trials.length>0,'micro-trials required');
  assert(resolveAgentIdentity===null||typeof resolveAgentIdentity==='function','agent identity resolver must be a function','ARMADA_IDENTITY_RESOLVER_INVALID');const ids=agents.map(a=>a.id);assert(ids.every(id=>typeof id==='string'&&id.length>0),'Armada agent ids are required','ARMADA_AGENT_ID_REQUIRED');assert(new Set(ids).size===ids.length,'Armada requires distinct agent ids','ARMADA_DUPLICATE_AGENT_ID');const identities=agents.map(agent=>{const resolved=resolveAgentIdentity?resolveAgentIdentity(agent):defaultIdentity(agent);assert(resolved&&typeof resolved.identityDigest==='string'&&resolved.identityDigest.length>0,'Armada agent identity incomplete','ARMADA_AGENT_IDENTITY_INCOMPLETE');return {provider:resolved.provider??null,model:resolved.model??null,identityDigest:resolved.identityDigest};});assert(new Set(identities.map(value=>value.identityDigest)).size===identities.length,'Armada requires distinct agent identities','ARMADA_DUPLICATE_AGENT');
  const candidateRuns=[];for(let index=0;index<agents.length;index+=1){const agent=agents[index],boundIdentity=identities[index];const trialResults=[];for(const trial of trials){const output=await executor({agent,mission,lane,trial,baseSha});const verified=await verifier({agent,mission,lane,trial,output,baseSha});assertIndependentVerifier({proposerId:agent.id,verifierId:verified.verifierId});trialResults.push(sealPlain({trialId:trial.id,taskDigest:digest({mission,lane,trial},'armada_task'),outputDigest:digest(output,'agent-output'),verification:verified}));}const score=trialResults.reduce((sum,r)=>sum+Number(r.verification.score??0),0)/trialResults.length;candidateRuns.push(sealPlain({agent:{id:agent.id,...boundIdentity},score,trialResults}));}
  candidateRuns.sort((a,b)=>b.score-a.score);const winner=candidateRuns[0];const receipt={receiptId:newId('allocation'),mission,lane,baseSha,consideredAgents:candidateRuns.map(r=>r.agent),candidateRuns,winnerAgentId:winner.agent.id,winnerScore:winner.score,createdAt:new Date().toISOString()};return sealPlain({...receipt,allocationDigest:digest(receipt,'intelligence-allocation')});
}
