import test from 'node:test';
import assert from 'node:assert/strict';
import {
  makeObservation, RealityGraph, buildDemandGraph, discoverOpportunities, preregisterExperiment,
  authorizeExperiment, startExperiment, settleExperiment, commitmentForSalt, makeAssignmentReceipt,
  makeExposureReceipt, makeOutcomeReceipt, makeReceipt, issueValueReceipt, proposeLesson, admitLesson,
  evaluateChallenger, runArmadaTournament, wraithAttack, auditKernelState, createCanonicalCanaAdapter,
  runReadOnlyOrganismCycle, createCanonicalEvidenceAdapter,
} from '../src/lib/cana-intelligence/index.mjs';

function evidenceHarness(actions=['AUTHORIZE_EXPERIMENT','EXECUTE_EXPERIMENT','SETTLE_EXPERIMENT','ADMIT_LESSON','PROMOTE_CHALLENGER']){
  const receipts=new Map(),lessons=new Map(),ledgers=new Map();
  const principal=makeReceipt({kind:'PRINCIPAL',subjectDigest:'owner:test',realm:'VERIFIED_LOCAL',issuer:'canonical-auth',payload:{verified:true,subject:'owner:test',allowedActions:actions}});receipts.set(principal.receiptDigest,principal);
  const adapter=createCanonicalEvidenceAdapter({loadReceipt:async d=>receipts.get(d)??null,loadLesson:async id=>lessons.get(id)??null,loadExperimentLedger:async id=>ledgers.get(id)??{assignments:[],exposures:[],outcomes:[]}});
  return {receipts,lessons,ledgers,principal,adapter,put:r=>receipts.set(r.receiptDigest,r)};
}
function obs(overrides={}){return makeObservation({entityKey:'merchant:m1',predicate:'price',value:40,sourceKind:'CANONICAL_REALITY',provenance:{source:'test'},observedAt:'2026-08-23T12:00:00Z',...overrides});}
function expInput(method='RANDOMIZED'){const salt='0123456789abcdef';return {salt,input:{hypothesis:'x',unit:'session',primaryMetric:'conversion',treatment:'A',comparator:'B',assignmentMethod:method,assignmentSaltCommitment:method==='RANDOMIZED'?commitmentForSalt(salt):null,exposureDefinition:'rendered treatment',analysisMethod:'two-proportion-z',minimumPerArm:20,stopRule:'after >=20 per arm',rollbackPlan:'restore prior',interferenceAssumptions:'no cross-unit interference',maximumClaimCeiling:'conversion lift for sampled population',proposerId:'agent:a'}};}
async function runExperiment({method='RANDOMIZED',effect=true,minimum=20}={}){const h=evidenceHarness();const {salt,input}=expInput(method);input.minimumPerArm=minimum;let exp=preregisterExperiment(input);exp=await authorizeExperiment(exp,h.adapter,h.principal.receiptDigest);exp=await startExperiment(exp,h.adapter,h.principal.receiptDigest);const assignments=[],exposures=[],outcomes=[];let c=0,t=0,i=0;while(c<minimum+10||t<minimum+10){const unitId=`u${i++}`; const a = method==='RANDOMIZED' ? makeAssignmentReceipt({experiment:exp,unitId,assignmentSalt:salt}) : makeReceipt({kind:'ASSIGNMENT',subjectDigest:exp.preRegDigest,realm:'VERIFIED_LOCAL',issuer:'observational-assignment',payload:{unitHash:`unit:${unitId}`,arm:(i%2?'CONTROL':'TREATMENT'),experimentId:exp.experimentId,preRegDigest:exp.preRegDigest}}); h.put(a); assignments.push(a.receiptDigest); a.payload.arm==='CONTROL'?c++:t++;const x=makeExposureReceipt({experiment:exp,assignmentReceipt:a,exposed:true,exposureEvidenceDigest:`exp:${i}`});h.put(x);exposures.push(x.receiptDigest);const success=effect?(a.payload.arm==='TREATMENT'?i%2===0:i%10===0):(i%5===0);const o=makeOutcomeReceipt({experiment:exp,exposureReceipt:x,success,outcomeEvidenceDigest:`out:${i}`});h.put(o);outcomes.push(o.receiptDigest);}h.ledgers.set(exp.experimentId,{assignments,exposures,outcomes});const settled=await settleExperiment(exp,h.adapter,h.principal.receiptDigest);return {h,exp,settled};}

test('simulator cannot become KNOWN',()=>assert.equal(obs({sourceKind:'SIMULATOR',requestedState:'KNOWN'}).epistemicState,'SYNTHETIC'));
test('observation timestamps are immutable strings',()=>assert.equal(typeof obs().observedAt,'string'));
test('evidence digest deterministic',()=>assert.equal(obs().evidenceDigest,obs().evidenceDigest));
test('temporal price change is succession not contradiction',()=>{const g=new RealityGraph([obs({value:40,observedAt:'2026-08-23T12:00:00Z'}),obs({value:45,observedAt:'2026-08-23T13:00:00Z'})]);assert.equal(g.resolve('merchant:m1','price').value,45);assert.notEqual(g.resolve('merchant:m1','price').epistemicState,'CONTRADICTED');});
test('overlapping validity windows with conflicting values contradict',()=>{const g=new RealityGraph([obs({value:40,validFrom:'2026-08-23T12:00:00Z',validTo:'2026-08-23T14:00:00Z'}),obs({value:45,observedAt:'2026-08-23T13:00:00Z',validFrom:'2026-08-23T13:00:00Z',validTo:'2026-08-23T15:00:00Z'})]);assert.equal(g.resolve('merchant:m1','price').epistemicState,'CONTRADICTED');});
test('demand graph rejects synthetic events',()=>assert.throws(()=>buildDemandGraph([{eventId:'e1',kind:'ASK',provenanceState:'SYNTHETIC',observedAt:new Date(),dimensions:{}}]),/OBSERVED/));
test('demand graph aggregates observed events',()=>{const g=buildDemandGraph([{eventId:'e1',kind:'ASK',provenanceState:'OBSERVED',observedAt:new Date(),dimensions:{market:'US-DC'}},{eventId:'e2',kind:'ZERO_RESULTS',provenanceState:'OBSERVED',observedAt:new Date(),dimensions:{market:'US-DC'}}]);assert.equal(g.totals.events,2);});
test('opportunity discovery exposes unmet demand',()=>{const events=Array.from({length:4},(_,i)=>({eventId:`e${i}`,kind:'ZERO_RESULTS',provenanceState:'OBSERVED',observedAt:new Date(),dimensions:{market:'US-DC',neighborhood:'Shaw',category:'flower',fulfillment:'delivery'}}));assert.equal(discoverOpportunities({demandGraph:buildDemandGraph(events),supply:[]})[0].kind,'UNMET_DEMAND');});
test('preregistration freezes minimum sample and analysis',()=>{const {input}=expInput();const e=preregisterExperiment(input);assert.equal(e.minimumPerArm,20);assert.equal(e.analysisMethod,'two-proportion-z');assert.ok(e.preRegDigest);});
test('authorization requires canonical principal receipt',async()=>{const h=evidenceHarness([]);const {input}=expInput();await assert.rejects(()=>authorizeExperiment(preregisterExperiment(input),h.adapter,h.principal.receiptDigest),/lacks AUTHORIZE_EXPERIMENT/);});
test('assignment salt commitment binds randomization',()=>{const {input}=expInput();const e=preregisterExperiment(input);assert.throws(()=>makeAssignmentReceipt({experiment:e,unitId:'u',assignmentSalt:'fedcba9876543210'}),/commitment mismatch/);});
test('settlement reads ledger and can support randomized causal effect',async()=>{const {settled}=await runExperiment({effect:true});assert.equal(settled.causalStatus,'CAUSALLY_SUPPORTED');assert.ok(settled.outcome.controlN>=20&&settled.outcome.treatmentN>=20);});
test('observational experiment cannot become causal',async()=>{const {settled}=await runExperiment({method:'OBSERVATIONAL',effect:true});assert.notEqual(settled.causalStatus,'CAUSALLY_SUPPORTED');});
test('outcome without exposure is refused',async()=>{const h=evidenceHarness();const {salt,input}=expInput();let e=preregisterExperiment(input);e=await authorizeExperiment(e,h.adapter,h.principal.receiptDigest);const a=makeAssignmentReceipt({experiment:e,unitId:'u1',assignmentSalt:salt});h.put(a);const fake=makeReceipt({kind:'OUTCOME',subjectDigest:e.preRegDigest,realm:'VERIFIED_LOCAL',issuer:'x',payload:{unitHash:a.payload.unitHash,success:true,outcomeEvidenceDigest:'o'}});h.put(fake);h.ledgers.set(e.experimentId,{assignments:[a.receiptDigest],exposures:[],outcomes:[fake.receiptDigest]});await assert.rejects(()=>settleExperiment(e,h.adapter,h.principal.receiptDigest),/without verified exposure/);});
test('economic receipt requires canonical AOV observation receipt',async()=>{const {h,settled}=await runExperiment({effect:true});const aov=makeReceipt({kind:'ECONOMIC_OBSERVATION',subjectDigest:settled.settlementDigest,realm:'VERIFIED_LOCAL',issuer:'analytics',payload:{metric:'AOV_USD',valueUsd:50}});h.put(aov);const r=await issueValueReceipt({settlement:settled,economics:{attributedAovReceiptDigest:aov.receiptDigest,costUsd:100},evidenceAdapter:h.adapter});assert.equal(r.economicStatus,'MEASURED_WITH_CAUSAL_SUPPORT');assert.ok(r.revenueImpactUsd>0);});
test('economic receipt refuses dollars without AOV receipt',async()=>{const {h,settled}=await runExperiment({effect:true});const r=await issueValueReceipt({settlement:settled,economics:{},evidenceAdapter:h.adapter});assert.equal(r.revenueImpactUsd,null);});
test('lesson admission requires causality and value receipt',async()=>{const h=evidenceHarness();const lesson=proposeLesson({claim:'x',scope:'merchant:m1',proposerId:'a',valueReceipt:{receiptDigest:'value:1',causalStatus:'CAUSALLY_SUPPORTED'}});const a=await admitLesson(lesson,{verifierId:'v',verdict:'ADMIT',evidenceDigest:'e'},h.adapter,h.principal.receiptDigest);assert.equal(a.trusted,true);assert.ok(a.admissionDigest);});
test('non-causal lesson cannot be trusted',async()=>{const h=evidenceHarness();const lesson=proposeLesson({claim:'x',scope:'m',proposerId:'a',valueReceipt:{receiptDigest:'v',causalStatus:'SUPPORTED_ASSOCIATION'}});const a=await admitLesson(lesson,{verifierId:'v',verdict:'ADMIT',evidenceDigest:'e'},h.adapter,h.principal.receiptDigest);assert.equal(a.trusted,false);});
test('RSI resolves canonical lesson and its admission/value receipts by id',async()=>{const h=evidenceHarness();const value=makeReceipt({kind:'VALUE',subjectDigest:'settlement:1',realm:'VERIFIED_REAL',issuer:'value-court',payload:{settlementClassification:'CAUSAL_SUPPORTED',realEconomicValueEstablished:true}});h.put(value);const admission=makeReceipt({kind:'LESSON_ADMISSION',subjectDigest:'lesson:digest:1',realm:'VERIFIED_REAL',issuer:'verifier:v',payload:{lessonId:'l1',verdict:'ADMIT',causalEnough:true,realEnough:true,valueReceiptDigest:value.receiptDigest}});h.put(admission);h.lessons.set('l1',{lessonId:'l1',lessonDigest:'lesson:digest:1',trusted:true,status:'ADMITTED',causalStatus:'CAUSAL_SUPPORTED',admissionDigest:admission.receiptDigest,valueReceiptDigest:value.receiptDigest,settlementDigest:'settlement:1'});const t=await evaluateChallenger({incumbent:{v:1},challenger:{v:2},lessonId:'l1',cases:[1],evaluator:async({mechanism})=>({score:mechanism.v,criticalRegressions:0}),ablator:async()=>({lessonContributionEstablished:true,lessonId:'l1'}),verifierId:'v',proposerId:'a',evidenceAdapter:h.adapter,principalReceiptDigest:h.principal.receiptDigest});assert.equal(t.verdict,'CHALLENGER_WINS');assert.equal(t.realRsi,'NOT_ESTABLISHED');});
test('RSI rejects absent canonical lesson',async()=>{const h=evidenceHarness();await assert.rejects(()=>evaluateChallenger({incumbent:{},challenger:{},lessonId:'forged',cases:[1],evaluator:async()=>({score:1}),ablator:async()=>({lessonContributionEstablished:true}),verifierId:'v',proposerId:'a',evidenceAdapter:h.adapter,principalReceiptDigest:h.principal.receiptDigest}),/not found/);});
test('Armada requires distinct agents',async()=>{await assert.rejects(()=>runArmadaTournament({mission:'x',lane:'code',agents:[{id:'a',model:'m',provider:'p'},{id:'a',model:'m',provider:'p'}],trials:[{id:'t'}],executor:async()=>({}),verifier:async()=>({verifierId:'v',score:1})}),/distinct/);});
test('Armada selects independently verified winner',async()=>{const r=await runArmadaTournament({mission:'x',lane:'code',agents:[{id:'a',model:'m1',provider:'p1'},{id:'b',model:'m2',provider:'p2'}],trials:[{id:'t'}],executor:async({agent})=>({answer:agent.id}),verifier:async({agent})=>({verifierId:'v',score:agent.id==='b'?1:.5})});assert.equal(r.winnerAgentId,'b');});
test('Wraith can fail candidate',async()=>{const r=await wraithAttack({candidate:{x:1},proposerId:'a',attacks:[{id:'x'}],attacker:async()=>({broke:true}),judge:async()=>({verifierId:'v',verdict:'FAIL',severity:10})});assert.equal(r.passed,false);});
test('audit catches synthetic containment breach',()=>assert.equal(auditKernelState({observations:[{id:'o',sourceKind:'SIMULATOR',epistemicState:'KNOWN',provenance:{},evidenceDigest:'x'}]}).verdict,'FAIL'));
test('canonical adapter still refuses missing host functions',()=>assert.throws(()=>createCanonicalCanaAdapter({}),/missing/));
test('read-only organism cycle stops before authority',async()=>{const a=createCanonicalCanaAdapter({loadObservations:async()=>[obs()],appendObservation:async()=>{},loadIntentEvents:async()=>[{eventId:'e1',kind:'ASK',provenanceState:'OBSERVED',observedAt:new Date(),dimensions:{market:'US-DC'}}],loadVerifiedSupply:async()=>[],resolveVerifiedPrincipal:async()=>null,persistReceipt:async()=>{},persistLesson:async()=>{},persistPrediction:async()=>{},persistExperiment:async()=>{}});const c=await runReadOnlyOrganismCycle(a);assert.match(c.nextAuthorityBoundary,/PROPOSE_ONLY/);});
