import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
function git(dir,args){const r=spawnSync('git',['-C',dir,...args],{encoding:'utf8'});if(r.status!==0)throw new Error(r.stderr);return r.stdout.trim();}
test('process Armada uses isolated worktrees and independent verifier',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cana-armada-runner-')),repo=path.join(dir,'repo');await fs.mkdir(repo);git(repo,['init']);git(repo,['config','user.email','test@example.com']);git(repo,['config','user.name','Test']);await fs.writeFile(path.join(repo,'README'),'x');git(repo,['add','.']);git(repo,['commit','-m','base']);const baseSha=git(repo,['rev-parse','HEAD']),receipt=path.join(dir,'receipt.json'),cfg=path.join(dir,'config.json'),node=process.execPath;await fs.writeFile(cfg,JSON.stringify({mission:'fixture mission',lane:'architecture',repoRoot:repo,baseSha,receiptPath:receipt,agents:[{id:'a',provider:'fixture',model:'A',command:node,args:[path.join(here,'fixtures/fake-agent.mjs'),'a']},{id:'b',provider:'fixture',model:'B',command:node,args:[path.join(here,'fixtures/fake-agent.mjs'),'b']}],verifier:{id:'v',provider:'fixture-verifier',model:'V',command:node,args:[path.join(here,'fixtures/fake-verifier.mjs')]},trials:[{id:'t1',task:'x'}]},null,2));const run=spawnSync(node,[path.join(here,'armada-runner.mjs'),cfg,receipt],{encoding:'utf8'});assert.equal(run.status,0,run.stderr);const parsed=JSON.parse(await fs.readFile(receipt,'utf8'));assert.equal(parsed.winnerAgentId,'b');assert.equal(parsed.baseSha,baseSha);assert.equal(parsed.candidateRuns.length,2);});
test('runner refuses candidate/verifier same process identity',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cana-armada-id-')),repo=path.join(dir,'repo');await fs.mkdir(repo);git(repo,['init']);git(repo,['config','user.email','t@e.com']);git(repo,['config','user.name','T']);await fs.writeFile(path.join(repo,'x'),'x');git(repo,['add','.']);git(repo,['commit','-m','b']);const baseSha=git(repo,['rev-parse','HEAD']),cfg=path.join(dir,'c.json'),node=process.execPath,args=[path.join(here,'fixtures/fake-agent.mjs'),'a'];await fs.writeFile(cfg,JSON.stringify({mission:'x',lane:'x',repoRoot:repo,baseSha,agents:[{id:'a',provider:'p',model:'m',command:node,args},{id:'b',provider:'q',model:'n',command:node,args:[path.join(here,'fixtures/fake-agent.mjs'),'b']}],verifier:{id:'v',provider:'p',model:'m',command:node,args},trials:[{id:'t'}]}));const run=spawnSync(node,[path.join(here,'armada-runner.mjs'),cfg],{encoding:'utf8'});assert.notEqual(run.status,0);assert.match(run.stderr,/verifier process\/model identity/);});
